"""Auto-render `output/CONTRACT.md` from Pydantic field descriptions.

The contract documents what downstream consumers (generative-UI host LLM,
dashboards, automated reviewers) get from PREx. It ships with every
`prex review` invocation so the next layer always has a current spec.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, List, Optional, Type, get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from prex.schemas.brief import (
    Brief,
    BlastRadius,
    ChecklistBinding,
    ChecklistItem,
    HunkInsight,
    Novelty,
    ReviewBrief,
    ReviewPlan,
    ReviewStep,
)
from prex.schemas.graph import (
    CallerStub,
    Edge,
    ExternalRefNode,
    FileNode,
    Graph,
    HunkNode,
    ModuleNode,
    PRMetadata,
    SymbolNode,
)
from prex.schemas._shared import Citation, Diagnostic, LineRange


# ---------- helpers ----------


def _annotation_str(ann: Any) -> str:
    if ann is None or ann is type(None):
        return "None"
    origin = get_origin(ann)
    if origin is None:
        return getattr(ann, "__name__", str(ann)).replace("typing.", "")
    args = get_args(ann)
    arg_strs = [_annotation_str(a) for a in args]
    name = getattr(origin, "__name__", str(origin))
    if name == "list" or name == "List":
        return f"List[{', '.join(arg_strs)}]"
    if name == "dict" or name == "Dict":
        return f"Dict[{', '.join(arg_strs)}]"
    if name == "tuple" or name == "Tuple":
        return f"Tuple[{', '.join(arg_strs)}]"
    if name == "Literal":
        return "Literal[" + " | ".join(repr(a) for a in args) + "]"
    if name == "Union" or str(origin) == "typing.Union":
        # Optional[T] simplification
        non_none = [a for a in args if a is not type(None)]
        if len(non_none) == 1:
            return f"Optional[{_annotation_str(non_none[0])}]"
        return " | ".join(arg_strs)
    return f"{name}[{', '.join(arg_strs)}]"


def _render_model_fields(model: Type[BaseModel]) -> str:
    """Render a markdown table of fields for one Pydantic model."""
    fi: FieldInfo
    lines = ["| Field | Type | Required | Description |", "|---|---|---|---|"]
    for name, fi in model.model_fields.items():
        ann = _annotation_str(fi.annotation)
        required = "yes" if fi.is_required() else "no"
        desc = (fi.description or "").replace("\n", " ").replace("|", "\\|")
        lines.append(f"| `{name}` | `{ann}` | {required} | {desc} |")
    return "\n".join(lines)


def _section_for(model: Type[BaseModel], header_level: int = 3) -> str:
    """Render '<heading> Model.__name__\n<docstring>\n<table>' for one model."""
    h = "#" * header_level
    title = model.__name__
    doc = (model.__doc__ or "").strip()
    parts = [f"{h} {title}"]
    if doc:
        # First line summary; rest as paragraph.
        parts.append("")
        parts.append(doc)
    parts.append("")
    parts.append(_render_model_fields(model))
    parts.append("")
    return "\n".join(parts)


# ---------- the contract ----------


_HEADER_TMPL = """\
# PREx output contract

> **Generated by `prex review` on {ts}.** Re-rendered every run.

This document is the contract between **PREx** (which produces structured
PR-review artifacts) and **the next layer** that consumes them — most often a
generative-UI host LLM that turns these structures into UI components, but
also any dashboard, bot, or automated reviewer.

## 1. What this is

PREx output produced from `prex review <PR-URL>` against:
- **PR**: `{pr_url}` ({pr_repo}#{pr_number})
- **head**: `{head_sha}`
- **base**: `{base_sha}` (branch `{base_ref}`)

## 2. Files in this directory

| File | Purpose | Schema |
|---|---|---|
| `brief.json` | Briefing for the host LLM. PR-level hero block, ranked review plan, per-hunk insights, manifest checklist. **Read this first.** | `prex/schemas/dist/brief.schema.json` |
| `graph.json` | Full multigraph (nodes + edges + diff overlay). Use as the deep-link store for citations from `brief.json`. | `prex/schemas/dist/graph.schema.json` |
| `manifest.snapshot.yaml` | Copy of the resolved `.review/types.yaml` used for this run. Reproducibility only. | (YAML, no schema) |
| `CONTRACT.md` | This file. | (Markdown) |

The deeper `prex/schemas/dist/` directory ships four JSON Schemas:
`shared`, `graph`, `brief`, and `combined`. The combined file inlines every
PREx model under `$defs`; use it if your consumer prefers one file.

## 3. Brief structure

The `Brief` is the primary input to the next layer. Its top-level fields:
"""


_GRAPH_HEADER = """
## 4. Graph structure

`Graph` is the deep store. Reach into it only when following a `Citation`.
Top-level fields:
"""


_TAIL_TMPL = """
## 5. Citation discipline

Every prose field that PREx emits — `ReviewBrief.headline`,
`HunkInsight.one_liner`, `ReviewPlan.steps[*].{{what,why,impact}}`,
`ReviewPlan.overview` — carries `cites: List[Citation]`. A `Citation`
resolves in one of four ways:

| `kind` | `ref` format | Where to look |
|---|---|---|
| `node` | `<kind>:<id>` | A node in `graph.json#/nodes`. |
| `edge` | `<type>:<source>->-<target>` | An edge in `graph.json#/edges`. |
| `file_line` | `<repo-relative-path>#L<start>-L<end>` | The source repo at `pr.head_sha`. |
| `external_doc` | absolute URL | The web. |

**The next layer must render a fact only via its citation.** Unsourced prose
in PREx output is a validation error.

## 6. Derivation + score

Both `Node` and `Edge` carry `derivation` and `score` fields:

- `derivation: Literal["ast","diff","crossref_text","llm","manifest","heuristic"]` —
  where the fact came from. Use this for the "evidence" tag.
- `score: float` (0..1) — the resolver's trust. Use this for visual weighting.

## 7. What the next layer should NOT do

1. Don't paraphrase prose without keeping the original `cites` references.
2. Don't render an `Edge` whose `derivation == "llm"` without surfacing that
   the relationship was inferred (e.g. show a "verified by Claude" / "AI inferred"
   badge). Same for any `HunkInsight.one_liner`, headline, or plan prose.
3. Don't render `diagnostics` whose `level == "info"` to the end user — they
   are plumbing.
4. Don't sort `plan.steps` by anything other than `rank`. The order is the
   recommended reading order.

## 8. Streaming order

When PREx adds streaming output (forthcoming), the emit order will be:

1. `pr` (PRMetadata)
2. `review.headline` (≤140 chars; first useful render)
3. `review` (full ReviewBrief)
4. `plan.overview`
5. `plan.steps[]` (top-down by rank)
6. `hunks[]`
7. `checklist[]`
8. `diagnostics[]`

The host LLM can begin rendering as soon as each block lands.

## 9. Versioning

`Graph.schema_version = "{graph_version}"`, `Brief.schema_version = "{brief_version}"`.
PREx is in build phase; bumps may be **non-back-compat**. Pin both.

## 10. Examples

See `output/graph.json` and `output/brief.json` in this directory for the actual
data produced for **{pr_repo}#{pr_number}**. Both files validate against their
respective schemas in `prex/schemas/dist/`.
"""


def render(pr_meta, *, graph_schema_version: str, brief_schema_version: str) -> str:
    parts: List[str] = []
    parts.append(
        _HEADER_TMPL.format(
            ts=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            pr_url=pr_meta.url,
            pr_repo=pr_meta.repo,
            pr_number=pr_meta.number,
            head_sha=pr_meta.head_sha,
            base_sha=pr_meta.base_sha,
            base_ref=pr_meta.base_ref,
        )
    )
    # Brief structure — top-level + supporting models.
    parts.append(_section_for(Brief, header_level=4))
    parts.append("Supporting models referenced by `Brief`:")
    parts.append("")
    for m in (ReviewBrief, BlastRadius, Novelty, ReviewPlan, ReviewStep, HunkInsight, ChecklistBinding, ChecklistItem):
        parts.append(_section_for(m, header_level=4))

    parts.append(_GRAPH_HEADER)
    parts.append(_section_for(Graph, header_level=4))
    parts.append("Supporting models referenced by `Graph`:")
    parts.append("")
    for m in (PRMetadata, ModuleNode, FileNode, SymbolNode, CallerStub, HunkNode, ExternalRefNode, Edge):
        parts.append(_section_for(m, header_level=4))

    parts.append("Shared primitives (live in `prex/schemas/_shared.py`):")
    parts.append("")
    for m in (LineRange, Citation, Diagnostic):
        parts.append(_section_for(m, header_level=4))

    parts.append(
        _TAIL_TMPL.format(
            graph_version=graph_schema_version,
            brief_version=brief_schema_version,
            pr_repo=pr_meta.repo,
            pr_number=pr_meta.number,
        )
    )
    return "\n".join(parts)


def write_contract(out_path: Path, pr_meta) -> None:
    text = render(
        pr_meta,
        graph_schema_version="0.2.0",
        brief_schema_version="0.1.0",
    )
    out_path.write_text(text)
